MODEL:
  NETWORK: vqvae
  CLASSIFIER: Classifier

DATASETS:
  TRAIN: '/Data/Proteins2021/CaCL/training'
  TEST: '/Data/Proteins2021/CaCL/test'

SOLVER:
  LR: 3e-4
  BATCH: 1
  EPOCH: 100
  GPU: 1
  NUM_WORKERS: 8

INPUT:
  CROP_SIZE: 128
  SIZE: 128

OUTPUT:
  ROOT: 'binary_test'
  CHECKPOINT: 'checkpoint_test'

TPARAMETER:
  PRETRAIN: 0
  NETWORK:
  CLASSIFIER:
  POOL: 32
  SELFTEST: 0
  MORPHOLOGY: 1
  RECON: 1
  EMBED_DIM: 64
  POS_DIM: 32
  N_EMBED: 32
  POS_EMBED : 5
  
  


